modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Ranzeplay/saysth/issues"
license = "MIT"

[[mods]]
modId = "saysth"
version = "${version}"
displayName = "SaySomething"
authors = "Jeb Feng"
description = '''

'''
#logoFile = ""

[[dependencies.saysth]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.saysth]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.saysth]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"
